[build]
  command = "npm install --prefix frontend && npm run build --prefix frontend"
  publish = "frontend/build"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_OMIT_KEYS = "REACT_APP_API_BASE_URL,REACT_APP_API_URL"
  REACT_APP_FIREBASE_API_KEY = "AIzaSyAahPR8zk3cyofh9DVQdJcTxl_Oj7uP5Sw"
  REACT_APP_FIREBASE_AUTH_DOMAIN = "thform-33f71.firebaseapp.com"
  REACT_APP_FIREBASE_PROJECT_ID = "thform-33f71"
  REACT_APP_FIREBASE_STORAGE_BUCKET = "thform-33f71.firebasestorage.app"
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID = "561503565164"
  REACT_APP_FIREBASE_APP_ID = "1:561503565164:web:399c0a21526e33c0012f49"
